version: "3"

networks:
  monitoring:
  app:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    command:
      - "-c"
      - "config_file=/psql/data/postgresql.conf"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./postgresql.conf:/psql/data/postgresql.conf
      - ./log:/var/lib/postgresql/data/log
    networks:
      - app
  filebeat-psql:
    image: docker.elastic.co/beats/filebeat:6.5.1
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/var/log:ro
    networks:
      - monitoring 
    depends_on:
      - logstash
  logstash:
    image: logstash:6.5.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - monitoring 
  elasticsearch:
    image: elasticsearch:6.5.1
    environment:
      - discovery.type=single-node
    networks:
      - monitoring 
  kibana:
    image: kibana:6.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - monitoring 
  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgres:5432/postgres?sslmode=disable"
    networks:
      - app 
      - monitoring 
    depends_on:
      - postgres
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

