filebeat.config.modules.path: modules.d/*.yml

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3} UTC \[[0-9]{2}\] \w+:'
  multiline.negate: true
  multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: kibana:5601

