global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  
